In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

In [2]:
data_fake = pd.read_csv('Fake.csv')
data_true = pd.read_csv('true.csv')

In [ ]:
data_fake.head()

In [5]:
data_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
data_fake['class'] = 0
data_true['class'] = 1

In [7]:
data_fake.shape, data_true.shape

((23481, 5), (21417, 5))

In [8]:
data_fake_manual_testing = data_fake.tail(10)
for i in range (23480, 23470, -1):
    data_fake.drop([i], axis = 0, inplace = True)

data_true_manual_testing = data_true.tail(10)
for i in range (21416, 21406, -1):
    data_true.drop([i], axis = 0, inplace = True)

In [9]:
data_fake.shape, data_true.shape

((23471, 5), (21407, 5))

In [10]:
data_fake_manual_testing['class'] = 0
data_true_manual_testing['class'] = 1

C:\Users\asus\AppData\Local\Temp\ipykernel_16856\277247672.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_fake_manual_testing['class'] = 0
C:\Users\asus\AppData\Local\Temp\ipykernel_16856\277247672.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_true_manual_testing['class'] = 1

In [11]:
data_merge = pd.concat([data_fake, data_true], axis = 0)
data_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [12]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [13]:
data = data_merge.drop(['title', 'subject', 'date'], axis = 1)

In [14]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [15]:
data = data.sample(frac = 1)

In [16]:
data.head()

                                                    text  class
8930   Gun nuts are a strange breed. They are paranoi...      0
2240   If one thing has become abundantly clear, it s...      0
20827  Outspoken British actress and columnist asks b...      0
15352  The LGBT Mafia and PC Police doing what they d...      0
11087  OMG. Why do these two gems of social media not...      0

In [17]:
data.tail()

                                                    text  class
5428   As Republicans gather for the first day of the...      0
16811  London is about to find out why putting politi...      0
1450   Last night, Trump International Hotel in Washi...      0
16744                                                         0
21893   Attacks against us are increasing in frequenc...      0

In [18]:
data.head(50)

                                                    text  class
8930   Gun nuts are a strange breed. They are paranoi...      0
2240   If one thing has become abundantly clear, it s...      0
20827  Outspoken British actress and columnist asks b...      0
15352  The LGBT Mafia and PC Police doing what they d...      0
11087  OMG. Why do these two gems of social media not...      0
17650  YANGON (Reuters) - Rohingya Muslims are not na...      1
17894  The backlash from angry fans has only gotten b...      0
13211  HARARE (Reuters) - Zimbabwe s new president Em...      1
22667  21st Century Wire says The issue of honest pol...      0
20905  According to insider, and author Edward Klein,...      0
13866  BEIRUT (Reuters) - Elections organized by the ...      1
14159  Priorities priorities Arizona Sen. John McCain...      0
5080   After all the backlash Trump received for sayi...      0
18718  Nathan Domingo is the founder of  Identity Eur...      0
5489   No matter how well dressed, or how intelligent...      0
22345  RTThe father of the Cuban Revolution remains u...      0
1838   When people talk about the threat that Donald ...      0
11212  Judge Napolitano explains what s going on as o...      0
21922  It should also be said that the current US Adm...      0
13244  CAIRO (Reuters) - Former Egyptian prime minist...      1
8749   President Obama has done something that no oth...      0
8769   Texas Christian Pastor Cindy Jacobs stood in f...      0
5148   MOSCOW (Reuters) - Russian Foreign Minister Se...      1
20948  BOGOTA (Reuters) - Colombia s notorious Golfo ...      1
2744   NEW YORK (Reuters) - The White House is hiring...      1
14349  BERLIN (Reuters) - German President Frank-Walt...      1
15543  One more Republican doing his part to aid Obam...      0
10855  A Navy SEAL Carl Higbie was blasted and screec...      0
6213   WASHINGTON (Reuters) - Kevin Hassett, an econo...      1
12428  Donald Trump values loyalty in a big way so wh...      0
13655  ROME (Reuters) - An Italian judge ruled on Tue...      1
1349   KIEV (Reuters) - Turkey’s President Tayyip Erd...      1
7083   Donald Trump has suggested that women should f...      0
15205  Andrew Breitbart got under the skin of the lef...      0
15357  Thoughts on the first GOP Presidential Primary...      0
8549   A couple of days ago a woman in Washington was...      0
136    WASHINGTON (Reuters) - The Trump administratio...      1
14419  It s difficult to look at Romney coming out ag...      0
10471  (Reuters) - Former New York City Mayor Michael...      1
2634   Not too long after CNN said they would no long...      0
3883   NEW YORK/WASHINGTON (Reuters) - The U.S. gover...      1
9896   President Trump just made an 11-year old boy s...      0
19929  The first Black (and half White) President has...      0
8780   The Republican Party is an absolute mess and w...      0
10815  Israeli First Lady Sara Netanyahu: I talk ever...      0
12070        https://www.youtube.com/watch?v=0cVugq2GbBk      0
19496  ANGELA Merkel today completed an astonishing U...      0
14130  JOHANNESBURG (Reuters) - South Africa s Deputy...      1
22038  Tune in to the Alternate Current Radio Network...      0
8447   MEXICO CITY (Reuters) - Mexican President Enri...      1

In [19]:
data.tail(50)

                                                    text  class
6756   In the book, The World is Blue: How Our Fate a...      0
8805   WASHINGTON (Reuters) - U.S. House of Represent...      1
22262  21st Century Wire says In a Tweet, Donald Trum...      0
16825  Wisconsin is losing me on this one-no common s...      0
12098  SEOUL (Reuters) - South Korea s foreign minist...      1
12543  Please go to the BEST MULCH Facebook page and ...      0
21391  Who s laughing now  funny  guy?We asked everyo...      0
6395   In a strong southern drawl that makes his bigo...      0
5951   A new report reveals that Donald Trump swindle...      0
19461                                                         0
12776  KIEV (Reuters) - The head of the International...      1
4603   Not long before Donald Trump pathetically admi...      0
22220  21st Century Wire says The following interview...      0
14009   A new movie about the Clinton Grifters couldn...      0
4787   WASHINGTON (Reuters) - The United States will ...      1
18574  MANCHESTER, England (Reuters) - Gibraltar is v...      1
9676   WASHINGTON (Reuters) - Republican presidential...      1
4299   Nogales, Ariz. (Reuters) - U.S. Attorney Gener...      1
17130                THE GREAT QUESTION OF CITIZENSHIP        0
17906  ZURICH (Reuters) - More than one in three Swis...      1
4378   When you ve lost the support of the whole Reag...      0
5834   LONDON (Reuters) - A planned state visit to Br...      1
279    WASHINGTON (Reuters) - Democrat Al Franken fac...      1
8502   (Reuters) - Republican Donald Trump, a former ...      1
14746  BERLIN (Reuters) - Germany s spy chief has war...      1
19542  In what has to be considered an historic about...      0
8104   NEW YORK (Reuters) - U.S. society is uncomfort...      1
9129   (Reuters) - A federal judge refused to dismiss...      1
831    The story of Donald Trump Jr. s 2016 meeting w...      0
17462  ISIOLO, Kenya (Reuters) - An expelled student ...      1
20683  BERLIN (Reuters) - Christian Lindner, leader o...      1
1320   To Donald Trump, his popularity is everything,...      0
8251   GREENVILLE, N.C., Va./WASHINGTON (Reuters) - R...      1
6763   WASHINGTON (Reuters) - The White House said on...      1
22927  Tune in to the Alternate Current Radio Network...      0
7171   Trump s latest fiasco is so bad that it s blee...      0
3229   WASHINGTON (Reuters) - From the incomprehensib...      1
15773  Pray for these police officers, the innocent c...      0
10234  Remember when Chelsea Clinton faced the same s...      0
2791   WASHINGTON (Reuters) - President Donald Trump ...      1
1639   4fr4fr34f43fMainstream (FAKE) media refuses to...      0
11970  LONDON (Reuters) - Russia poses an increasing ...      1
18497  MOSCOW (Reuters) - A Russian court sentenced o...      1
3139   President-elect Donald Trump s massive swamp n...      0
10153  President Trump condemned hate groups today AG...      0
5428   As Republicans gather for the first day of the...      0
16811  London is about to find out why putting politi...      0
1450   Last night, Trump International Hotel in Washi...      0
16744                                                         0
21893   Attacks against us are increasing in frequenc...      0

In [20]:
data.reset_index(inplace = True)

In [21]:
data.drop(['index'], axis = 1, inplace = True)

In [22]:
data.columns

Index(['text', 'class'], dtype='object')

In [23]:
data.head()

                                                text  class
0  Gun nuts are a strange breed. They are paranoi...      0
1  If one thing has become abundantly clear, it s...      0
2  Outspoken British actress and columnist asks b...      0
3  The LGBT Mafia and PC Police doing what they d...      0
4  OMG. Why do these two gems of social media not...      0

In [24]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W", " ", text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

In [25]:
data['text'] = data['text'].apply(wordopt)

In [26]:
x = data['text']
y = data['class']

In [105]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [106]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [107]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train, y_train)

LogisticRegression()

In [108]:
pred_lr = LR.predict(xv_test)

In [109]:
LR.score(xv_test, y_test)

0.9872549019607844

In [110]:
print(classification_report(y_test, pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5830
           1       0.99      0.99      0.99      5390

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [129]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier(
    max_depth=20,
    min_samples_split=10,
    random_state=42
)
DT.fit(xv_train, y_train)

DecisionTreeClassifier(max_depth=20, min_samples_split=10, random_state=42)

In [112]:
pred_dt = DT.predict(xv_test)

In [113]:
DT.score(xv_test, y_test)

0.996524064171123

In [114]:
print(classification_report(y_test, pred_dt))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5830
           1       1.00      1.00      1.00      5390

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220

In [130]:
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
GB.fit(xv_train, y_train)

GradientBoostingClassifier(n_estimators=200, random_state=42)

In [131]:
pred_gb = GB.predict(xv_test)

In [132]:
GB.score(xv_test, y_test)

0.9962566844919786

In [133]:
print(classification_report(y_test, pred_gb))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5830
           1       1.00      1.00      1.00      5390

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220

In [120]:
from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(random_state = 0)
RF.fit(xv_train, y_train)

RandomForestClassifier(random_state=0)

In [121]:
pred_rf = RF.predict(xv_test)

In [122]:
RF.score(xv_test, y_test)

0.9896613190730837

In [123]:
print(classification_report(y_test, pred_rf))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5830
           1       0.99      0.99      0.99      5390

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [125]:
def output_lable(n):
    if n == 0:
        return "Fake"
    elif n == 1:
        return "Not Fake"

def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)
    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    pred_GB = GB.predict(new_xv_test)
    pred_RF = RF.predict(new_xv_test)

    return print("\n\nLR Prediction: {} \nDT Prediction: {} \nGB Prediction: {} \nRF Prediction: {}".format(output_lable(pred_LR[0]),
                                                                                                           output_lable(pred_DT[0]),
                                                                                                           output_lable(pred_GB[0]),
                                                                                                           output_lable(pred_RF[0])))

In [126]:
news = str(input())
manual_testing(news)

 In a surprise move that immediately sparked debate across industries, the Government of India on Monday announced a six-month nationwide pilot program testing a three-day workweek for select public and private sector organizations. The initiative, titled Project Samay, aims to study whether reduced working days can improve productivity, innovation, and overall well-being without harming economic output.  According to officials familiar with the plan, the trial will involve approximately 1.2 million employees across technology services, public administration, education, and research institutions. Participating employees will work three extended days of 10 hours each, followed by four consecutive days off. Salaries and benefits will remain unchanged during the trial period.  The policy was unveiled at a high-level press briefing in New Delhi, where policymakers claimed that traditional work models were “no longer aligned with how modern economies function.” Internal studies cited by the government suggested that long working hours were contributing to burnout, declining creativity, and rising healthcare costs, particularly among younger professionals.

LR Prediction: Not Fake
DT Prediction: Fake
GB Prediction: Fake
RF Prediction: Not Fake

In [127]:
news = str(input())
manual_testing(news)

 In a surprise move that immediately sparked debate across industries, the Government of India on Monday announced a six-month nationwide pilot program testing a three-day workweek for select public and private sector organizations. The initiative, titled Project Samay, aims to study whether reduced working days can improve productivity, innovation, and overall well-being without harming economic output.  According to officials familiar with the plan, the trial will involve approximately 1.2 million employees across technology services, public administration, education, and research institutions. Participating employees will work three extended days of 10 hours each, followed by four consecutive days off. Salaries and benefits will remain unchanged during the trial period.  The policy was unveiled at a high-level press briefing in New Delhi, where policymakers claimed that traditional work models were “no longer aligned with how modern economies function.” Internal studies cited by the government suggested that long working hours were contributing to burnout, declining creativity, and rising healthcare costs, particularly among younger professionals.

LR Prediction: Not Fake
DT Prediction: Fake
GB Prediction: Fake
RF Prediction: Not Fake

In [128]:
import joblib

joblib.dump(LR, "lr_model.pkl")
joblib.dump(DT, "dt_model.pkl")
joblib.dump(GB, "gb_model.pkl")
joblib.dump(RF, "rf_model.pkl")
joblib.dump(vectorization, "tfidf.pkl")

['tfidf.pkl']